_drafts/introduction-to-functional-programming-in-python-p1.md
_posts/2015-10-18-introduction-to-functional-programming-in-python-p1.md

The first post in the functional programming with python series, it
covers the following topics:
- Imperative vs Functional programming
- Pure vs Impure functions
If you could have a quick read it would be much appreciated also let me know if I need to correct anything or if I need to make something a bit clearer  :)

First post in functional programming with python series

---

_drafts/draft-blog-post.md

Converted a few simple things to more markdown syntax

Fix Markdown Syntax

---

_includes/catmenu.html
css/main.css

Here is a screenshot, hopefully this will work when on a mobile device as well
And another when even narrower

Fix css issues on narrow displays. #36

---

Gemfile
Rakefile

- Now we can run `bundle install` to install all dependencies for
building the site and running tests in one go. (This is when you are
in the same folder as the gem file)
- This requires you have `bundle` installed so simply run `gem install
bundle` to get it
- To run the tests simply run `rake` at the command line from the same
folder as the `Rakefile`
TODO: Set up a ruby equivalent of virtualenv to make things even easier
for us

Making it easier to run tests locally

---

.gitignore
_posts/2015-01-16-making-an-app-in-python-using-kivy-1.md
_posts/2015-01-28-making-an-app-in-python-using-kivy-2.md
_posts/2015-10-03-adding-python-to-the-path-windows.md
_posts/2015-10-13-the-first-editor-off.md
blog/Pydiff.html
blog/atom.html
blog/blog.html
blog/emacs.html
blog/functional.html
blog/kivy.html
blog/vim.html

Tests will most likely fail - due to changing URLs since jekyll uses the categories to create them

Removing uneeded categories

---

editors/idle.md

I did a thing :ambulance:

---

_drafts/draft-blog-post.md
_includes/catmenu.html
_includes/post_link.html
_layouts/language.html
_posts/2014-12-14-A-first-blog-post.md
_posts/2015-01-15-New-computers-for-code-club.md
_posts/2015-01-16-making-an-app-in-python-using-kivy-1.md
_posts/2015-01-28-making-an-app-in-python-using-kivy-2.md
_posts/2015-02-06-WHERE-IS-EVERYONE.md
_posts/2015-02-27-special-guest-to-code-club.md
_posts/2015-10-03-adding-python-to-the-path-windows.md
_posts/2015-10-29-How-I-made-a-DOS-at-school.md
editors/Atom.md
editors/Notepad.md
editors/index.md
getinvolved.html
index.html
languages/index.md
reference.html

All internal links should now be relative to the site root `/`

Make links testable again

---

_data/past_sessions.yml

I forgot about this through all the testing. :smiling_imp:

Adding this weeks session 

---

.travis.yml

Adding gitter integration with travis

---

.gitignore
.travis.yml
Gemfile
Rakefile
_includes/post_link.html
_posts/2015-12-04-code-and-go-game.md
editors/index.md
index.html
languages/index.md

_Note:_ These changes depend on the successful merge of #74 
Running `rake test` will now also validate all the html we generate with
jekyll. This ensures that all out html is well formed and that there are
no surprises.
This also includes a few minor fixes to make sure that the tests pass.
Addresses #70

Check html

---

_config.yml
_sass/_elements/_codesnippets.scss
_sass/_elements/_post.scss

So there was a few issues with the refactor (things were forgotten to be added/removed) hopefully this fixes them all

Code css fix

---

Rakefile
_config.yml

Just a small change I've had sitting off on a branch for a while now.
It slightly modifies some of the rake commands so that all the gems are sourced correctly

Adding pygments to the Rakefile

---

README.md
_layouts/language.html
_posts/2015-12-15-Introducing-micro-workshops.md
getinvolved.html

This gets rid of the extra space in the contributor title and should fix the tests. :smiling_imp:

extra space and broken tests

---

README.md
_layouts/language.html
_posts/2015-12-15-Introducing-micro-workshops.md
getinvolved.html

Revert due to micro workshops are broken, 
Reverts CardiffMathematicsCodeClub/CardiffMathematicsCodeClub.github.io#102

Revert "extra space and broken tests"

---

README.md
_config.yml

- Added a dedicated testing section
- Updated a few of the commands given to remove unecessary options
- Reformatted the markdown so most lines have length < 80 ;)
This should fix #81

Improvements to the README

---

_sass/_layouts/_base.scss

These 2 commits will fix the footer to the bottom of the windows for desktop users when the full menu bar is displayed

Fix footer to bottom for desktop users

---

_config.yml
script/link-checker.sh
workshops.md

Since a bunch of new content has been added and moved around since I did
this, I thought it was about time to update the tests again

Editing the link-checker.sh test

---

workshops.md

Wording of workshop page

---

_layouts/landingpage.html
_sass/_main/_landingpage.scss
_sass/_matrix/_landingpage.scss

I have added the footer to the landing page (see pic below), @alcarney now I know this is not how we discussed it would be done but this is simpilar and as far as I can tell it works. Also it didn't break travis on my fork so I guess it is fine?

Landing page footer

---

_sass/_layouts/_base.scss
_sass/_themes/_main/_base.scss
getinvolved.md

We currently have this:
This PR gives us this:

fixing issue with disclaimer

---

_data/themes.yml
css/matrix.scss

It has gone form this:
To this:

Making the visited links visible.

---

_data/sessions.yml

small fix. 

---

_sass/_layouts/_landingpage.scss
index.html

In the CSS I have added some padding to the <p> tag and <h2> tags

I have removed all the <br /> tags within <p> tags

---

_data/themes.yml
_sass/_layouts/_mixins.scss
_sass/_styles/_codesnippets.scss
_sass/_themes/_cardiffred/_base.scss
_sass/_themes/_cardiffred/_catmenu.scss
_sass/_themes/_cardiffred/_landing.scss
_sass/_themes/_cardiffred/_posts.scss
css/cardiffred.scss

I'm not very inventive with names, so since I use quite a bit of red in
this theme I am calling it "Cardiff Red"
This is my first stab at a theme and I think I will be tweaking it for
quite a while yet!
Here are the obligatory screenshots!

Adding Cardiff Red Theme

---

_config.yml
_data/themes.yml
_sass/_themes/_cardiffred/_landing.scss
_sass/_themes/_cardiffred/_sessions.scss
css/cardiffred.scss

- Adding support for past sessions
- Make the code club logo look like a badge

Tweaks to cardiff red theme

---

_projects/moduleplan.md

updating module planner github repo

---

_layouts/project.html
_projects/elbow.md
_projects/moduleplan.md
_projects/thegame.md
_projects/website.md

This should hopefully fix #178

Making it the mobile site hopefully nice again

---

_data/themes.yml
_sass/_themes/_cardiffrouge/_base.scss
_sass/_themes/_cardiffrouge/_catmenu.scss
_sass/_themes/_cardiffrouge/_landing.scss
_sass/_themes/_cardiffrouge/_posts.scss
_sass/_themes/_cardiffrouge/_sessions.scss
css/cardiffrouge.scss

This adds a new theme cardiff rouge, a lighter version of Cardiff Red

New theme! Cardiff Rouge

---

css/main.scss

New background color

---

_data/contributors.yml
_data/sessions.yml
_data/themes.yml
_sass/_layouts/_base.scss
_sass/_themes/_main/_base.scss
css/inverted.scss
css/lime.scss
css/main.scss
css/matrix.scss
css/pink.scss
css/red.scss
css/yellow.scss

Adding themes and stuff

---

_includes/common_head.html
_includes/twitter_feed.html
_layouts/blog.html
_layouts/default.html
_layouts/landingpage.html
_sass/_layouts/_base.scss
_sass/_layouts/_mixins.scss
_sass/_themes/_cardiffred/_base.scss
js/twitter.js

As you may or may not know, code club now has its own twitter account!
This adds the twitter feed onto the site so vistors can see it.
I really struggled on where to put this and still have it look good
accross all devices and I think what I have come up with works ok, but
please let me know your thoughts :)
Rather than display the feed at all times, the feed is 'minimised' and
the only thing that is visible is a tab at the bottom right of the
screen which says "Twitter", clicking on this will cause the feed to be
displayed with a nice entry animation. Clicking again will hide it.
Please see screenshots for more info :)
**IMPORTANT!:** While I have added the necessary CSS to the default
layout of the site so that it is positioned correctly on all themes,
it's up to the theme makers to …

Add Twitter Timeline!

---

_includes/footer.html

This tweaks the footer template so that theme names in the dropdown are
now sorted alphabetically.

Themes are now sorted in the dropdown

---

README.md

Adding link to the documentation

---

_data/themes.yml
_sass/_themes/_cardiffred/_base.scss
_sass/_themes/_cardiffred/_sessions.scss

- Added extra padding to the menu items
- Added extra padding to sessions page so things look nicer
- Added style rules for elements `h3`, `h4`, `h5`, `h6`
- Minor version bump

Tweaks to Cardiff Red

---

_data/themes.yml
_sass/_themes/_cardiffrouge/_base.scss
_sass/_themes/_cardiffrouge/_landing.scss
_sass/_themes/_cardiffrouge/_sessions.scss
js/twitter.js

- Added padding to the menu
- Added styles for `h3`, `h4`, `h5`, `h6`
- Styled the twitter tray
- Added a black border to everything so that it looks sharper
- Minor version bump

Tweak Cardiff Rouge

---

_data/themes.yml
_sass/_themes/_cardiffrouge/_base.scss
_sass/_themes/_cardiffrouge/_posts.scss
css/cardiffrouge.scss

A few more tweaks to cardiff rouge:
- Adding a border to disqus comments
- Making the shadow around objects more subtle
- Making code snippets look like they are embedded in the page rather
than floating above it
- Internal refactoring
- Minor version bump

Tweaks to Cardiff Rouge

---

_layouts/blog.html
blog/events.html
blog/index.html
blog/news.html
blog/pydiff.html
blog/tutorial.html

So it turns out the system I had set up relied on a "bug" that was fixed
in Jekyll v3.1.4, thankfully the fix is easy.

Fix broken blog layout

---

index.html

Only front page edited. There may be other references to the day elsewhere.

Altered day - changed Thurs to Weds
