CardiffMathematicsCodeClub/CardiffMathematicsCodeClub.github.io

_includes/catmenu.html
_includes/post_link.html
_layouts/blog.html
_layouts/catpage.html
_posts/2015-01-16-making-an-app-in-python-using-kivy-1.md
_posts/2015-01-28-making-an-app-in-python-using-kivy-2.md
blog/atom.html
blog/blog.html
blog/emacs.html
blog/functional.html
blog/index.html
blog/kivy.html
blog/pydiff.html
blog/python.html
blog/tutorial.html
blog/vim.html
blog/website.html
css/main.css
index.html

This is a rather big set of changes so, hold on to your hats...
The blog page now has a category menu! This means the following:
- The blog page now has its own layout in `_layouts` called `blog.html`
- You can now filter blog posts according to the categor(y/ies) that
they are placed in
- By clicking on a category you are taken to a category page (these
have to be added by hand - more on that later)
- Since the category pages also need a category menu this has been
abstracted out into `_includes/catmenu.html`. This is included in
both `_layouts/blog.html` and `_layouts/catpage.html`
- To create a category page simply create a HTML file with the new
category's name in the `/blog` folder and add the following to the
YAML front matter:
+ layout: catpage
+ category: <catname>
where of course …

Adding blog category pages and a few minor improvements

---

README.md
_data/contributors.yml
getinvolved.html
index.html

This makes the contributor title a link to the contributor's github page. As you can see in the gif below.
:smiling_imp:

Githublinks

---

_data/menu.yml
_data/projects.yml
getinvolved.html
index.html
languages/brainfk.md
reference.html

- Projects can now be toggled as 'active' or 'not active'
- To mark a project as active simply add `active: true` to the project's
data in `_data/projects.yml`
- Active projects are listed on the getinvolved page with a link to the
full list of projects
- Divided languages between "real" languages and "forfun" languages and
have seperate sections for them on the main reference page
- To mark a language as "forfun" simply add the tag `forfun` in the YAML
front matter of the language's page
- Programming challenges have been moved from the reference page to the
getinvolved page
- Updated home page content to reflect the new structure of the site

Rewriting the reference and getting involved pages

---

.travis.yml
Rakefile
languages/clojure.md
script/cibuild

So it turns out the regexp we were using to ignore the code club links was incorrect, that has been fixed now also we now call `htmlproofer` from our `Rakefile`. There are many other options we can tweak and I might play with those in future...
However it might be a good idea to let the dust settle for a while...

Fixing the tests once and for all

---

Rakefile

By only asking `html-proofer` to fail on 4xx errors then it should only report on errors we can do something about i.e. fixing broken links rather than internal server errors on other sites etc. (5xx erorrs)

This might fix the tests

---

_data/contributors.yml
_data/past_sessions.yml
getinvolved.html
sessions.html

So for a while now I have wanted to change the way we add the session quote auther. Basicaly I wanted to come up witha way to make the session author atumatically a person's title if they were a site contributor, ie I type `alex` as the author and on the website it would show up as `Leonardo`.  Now this could have been done with a for loop and an if statement but it made sessions.html look very messy and I want all of the code to be presentable enough so that people can look at it and instantly understand what is going on.
Alex suggested that I change the contributors.yml file to the same style as the projects.yml file and use the assign function.  So now when we go to write the session detailes we just put the auother down as by the person first name, ALL IN LOWERCASE, if they are a …

New way to add past sessions and contributors

---

.travis.yml
Gemfile
Rakefile

- __IMPORTANT:__ the default behavoir of `rake` is now to list all
available tasks __NOT__ run the tests
- Tests now have to be explicitly run with `rake test`. `.travis.yml`
has been updated to reflect this
- We have three new commands:
+ newpost
+ publishpost
+ drafts
newpost:
- New draft posts can be made using the following command
```
$ rake newpost\[name-of-post\]
```
or equivalently
```
$ rake "newpost[name-of-post]"
```
_Note:_ `name-of-post` should contain lowercase letters and no spaces
- This command will create a new markdown file `_drafts/name-of-post.md`
as long as is doesn't already exist
- The file will contain boilerplate yaml frontmatter:
```
---
layout: post
title: YOUR TITLE HERE
categories: CATEGORY
tags: TAGS
author: YOUR NAME
---
Your awesome blog post goes here. …
```

Rake improvements

---

Gemfile
_config.yml
_includes/pagination_nav.html
_layouts/blog.html
_sass/_base.scss
_sass/_elements/_base.scss
_sass/_layouts/_multicolumn.scss
_sass/_layouts/_postlists.scss
blog/index.html
css/main.scss
index.html

We now have quite a few blog posts - and it's only going to get more in
the future, so we can now split the long lists of posts into many
shorter pages using jekyll's built in pagination features.
- This adds "Next" and "Previous" buttons to the bottom of each page in
the blog (not the category pages)
- The html for the buttons is defined in `_includes/pagination_nav.html`
Here are a few screenshots

Added blog pagination

---

_posts/2014-12-14-A-first-blog-post.md
_posts/2015-01-15-New-computers-for-code-club.md
_posts/2015-02-06-WHERE-IS-EVERYONE.md
_posts/2015-02-27-special-guest-to-code-club.md
_posts/2015-09-28-Just-in-time-for-the-new-term-PyDiff.md
_posts/2015-10-13-the-first-editor-off.md
_posts/2015-10-29-How-I-made-a-DOS-at-school.md
blog/news.html

This might make more sense since most of these posts are updates about
general things at code club, new computers, pydiff, dog visits etc.
Also this would reduce confusion between the website category and the
website tag (which the latter is used to extract relevant articles from
the blog to be listed on the code club website project page)

Proposal: Rename website category to news

---

_workshops/2015-2016/the-command-line.md

Pushing the date back a week to the 4th of Feb so that the first years have
chance to find out about it.

Changing date of command line workshop

---

README.md
_config.yml
hooks/pre-commit

So the recent theme changer PR also added a version number to the footer
on the website, currently sat at 3.5.0. This PR now adds a `pre-commit`
script which runs before each commit you make (see below).
The script:
1. Fetches all tags from the upstream repository
2. Looks at the latest tag and extracts the major and minor versions
from it
3. It then looks at the number of commits since that release and adds
that as the patch version
4. It finally does a serach and replace in `_config.yml` to update the
version number.
*IMPORTANT:* For this to work you need to do the following:
- Symlink the script into the actual git hooks directory, by running the
following from the `hooks` directory
```
$ ln -s pre-commit ../.git/hooks
```
- Have the `upstream` remote set up to this repository
- Ensure …

Calculating version numbers

---

_config.yml

This enables an option in our `_config.yml` which compresses (or minifies if we want to be posh) the css generated by sass.
This means that the css that sits on the live website wouldn't have any whitespace and therefore be a much smaller file for people to download when they visit.
This should also mean that changing themes will work quicker as well

Minify CSS

---

_includes/header.html
_includes/menu.html
_sass/_main/_landingpage.scss
index.html

So it turns out I was being too fancy with the html and the landing page styles were overriding the styles on the rest of the site causing menus on mobile to turn invisible.
Fixed now :) (hopefully)

Fixing invisible menus on mobile

---

_includes/catmenu.html
_includes/post_link.html
_layouts/catpage.html
_layouts/post.html

- Both on the category menu and the category page titles the category name
is now capitalised
- Tweaked the info line below post titles so that it includes a link to
the category that the post has been posted in.

Minor template tweaks

---

_includes/catmenu.html

Instead of having "All Posts" be another header like "Posts by Category"
it now looks like another category which I hope looks a bit better

Tweaking the category menu

---

script/cibuild

Travis will now give a breakdown on how long it takes to build each part
of the website, this may allow us to look at reducing bottlenecks in the
building of the site

Enabling profiling of builds

---

_includes/twitter_card_post.html
_layouts/default.html

- This is an experiment having just come accross
[twitter cards.](https://dev.twitter.com/cards/types/summary)
- By adding a few `<meta>` tags in our html, whenever people tweet a
link to the website, twitter scrapes the linked page looking for these
tags and if they are found displays a nice looking card in the body of
a tweet.
- This PR is an attempt to add the necessary meta tags to implement
this for blog posts.
- I have also created a twitter account for code club (no idea if people
want this so currently it's not really visible - I want to hear your
thoughts on this.)
- If people decide they want a twitter account for code club then these
cards can be linked to the account and we in theory can get some
metrics on how people interact with tweets containing links to the
site (again no …

Add twitter cards for blog posts

---

_sass/_layouts/_base.scss
_sass/_themes/_cardiffred/_base.scss

So having both logos be displayed at once is dumb and looks stupid so
this now sets a default in the `_sass/_layouts/_base.scss` file as with
the twitter feed theme.
The default is the **blue** logo as it should be visible on most themes
we currently have. If you want the blue logo then you don't have to
change anything.
If you want to change from the default to the white logo then you need
to add the following CSS to your theme:
```
.sidetab > .blue {
display: none;
}
.sidetab > .white {
display: block;
}
```

Choosing a default logo for the twitter feed

---

_config.yml
script/bump-version.sh

For a few months now there's been a script `hooks/pre-commit` which
calculates the version of the code club website according to the
scheme `<major>.<minor>.<patch>`. Where the major and minor versions are
set by the latest tag and the patch number is simply the number of
commits that have been made since the last version tag.
The original idea was to have this run everytime people make a commit on
the site, however after a few trial runs we found that this caused
neverending merge conflicts since everyone was editing the same line in
the same file.
But there's nothing wrong with someone running the script from time to
time to bump the version number, so this commit simply moves and renames
this script so that it is more obvious to everyone what it is.
The script is now called …

Version bump and script

---

_includes/twitter_feed.html
_sass/_themes/_cardiffred/_base.scss

This tweaks the twitter widgets so that they are actually all on screen
correctly rather than stopping halfway down.
This also fixes the cardiff red theme which was actually displaying
both timelines at once.
**IMPORTANT:** The widgets that are on the live site no longer exist so
the feed is currently broken on the live site (I deleted them before
realising it affected the site)

Fixing twitter

---

_sass/_layouts/_base.scss

On mobile I've found the browser to get confused when scrolling on 
the twitter feed. Often it will also scroll the page behind the feed and 
produce visual glitches. This is a test to see if elevating the element
will fix it

Testing z-index for twitter feed

---

_config.yml
_docs/index.md
_docs/project-structure.md
_layouts/project.html
_posts/2014-12-14-A-first-blog-post.md
_posts/2015-01-15-New-computers-for-code-club.md
_posts/2015-12-15-Introducing-micro-workshops.md
_posts/2016-02-10-introducing-themes.md
_projects/website.md

- Documentation
It's finally happening the code club website is getting documented! This
adds a new collection `_docs` and the very first piece of documentation
"Project Structure". This just gives an overview as to what each folder
and file is for in the root of the repository on Github, hopefully so
that people new to the site aren't overwelmed when they see it for the
first time.
This should help with #119 and #19 
- Project News
This tweaks the project template so that any blog post which is filed
under "news" and is tagged with that project's tag will show up on it's
project page.
Also added a link to the documentation for the code club website.

Document all the things!

---

_config.yml
_docs/index.md
_docs/project-structure.md
_layouts/default.html
_layouts/project.html
_posts/2014-12-14-A-first-blog-post.md
_posts/2015-01-15-New-computers-for-code-club.md
_posts/2015-12-15-Introducing-micro-workshops.md
_posts/2016-02-10-introducing-themes.md
_projects/website.md
js/docsearch.js

This depends on #207 
Using [lunr.js](http://lunrjs.com) and following [this](http://katydecorah.com/code/lunr-and-jekyll/) excellent guide,
we can now search the documentation! It isn't great just yet since
there is only two items in the documentation for now, but as
more and more it added it should become quite useful.
Although we still need to create some sort of structure as well since it
would help first time users find out what is actually documented.
In order to implement this I ended up modifying the
`_layouts/default.html` template, this adds support for a new
frontmatter term `script`
The `script` item can be used to add extra javascript scripts to the
head of an HTML document without the need for defining an entirely new
layout just for that.
Let me know what you think, do we …

Add searching the documentation

---

_layouts/project.html

This fixes a typo on the project page template which caused the date for
each news item to be the date that the page was generared, rather than
the date that the actual news item was written.

Fix typo on project template

---

_languages/C++.md
_languages/C.md
_languages/brainfk.md
_languages/clojure.md
_languages/haskell.md
_languages/java.md
_languages/python.md
_layouts/language.html
reference.md

This should go some way towards closing #25 
- This finally adds the Haskell language page to the website! :metal:
- Reworded parts of the C language page since I can't English
- Tweaked some template code so we no longer have to specify the `title`
in the language pages. The templates are now smart enough to work out
the title from the `language` attribute

Adding Haskell page!
